---
apiVersion: v1
kind: ConfigMap
metadata:
  name: questcode
  namespace: prod
data:
  NODE_ENV: production
  GITHUB_CLIENT_ID: dee0d79b7df90c4de83c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: questcode
  namespace: staging
data:
  NODE_ENV: staging
  GITHUB_CLIENT_ID: dee0d79b7df90c4de83c
---